---
################################################################################
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

- name: Add GPG key for magma repository
  apt_key:
    url: https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public
    state: present
    
- name: Remove deprecated Getenvoy.io repo
  apt_repository:
    repo: "deb https://dl.bintray.com/tetrate/getenvoy-deb stretch Release"
    state: absent
  debugger: true

- name: Remove deprecated Getenvoy.io repo
  file:
    path: /etc/apt/sources.list.d/dl_bintray_com_tetrate_getenvoy_deb.list
    state: absent
  debugger: true

- name: Add apt-transport-https
  apt: pkg=apt-transport-https state=present update_cache=yes
  #  when: preburn

- name: Add JFrog key
  apt_key:
    url: https://facebookconnectivity.jfrog.io/artifactory/api/gpg/key/public
    state: present

- name: Add JFrog repo
  apt_repository:
    repo: 'deb https://facebookconnectivity.jfrog.io/artifactory/list/{{ repo }}/ {{ distribution }} main'
    update_cache: yes
    mode: 0644
