{{/*
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: control-proxy
  name: controlproxy-config
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
data:
  gw_challenge.b64: |
    {{ print .Values.config.gwChallenge | trim | nospace }}
  control_proxy.yml: |
    # Cloud address for reaching out to the cloud.
    cloud_address: controller.{{ .Values.config.domainName }}
    cloud_port: 443

    bootstrap_address: bootstrapper-controller.{{ .Values.config.domainName }}
    bootstrap_port: 443

    fluentd_address: fluentd.{{ .Values.config.domainName }}
    fluentd_port: 24224
