{{/*
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}
---
{{- include "agwc.deployment" (list . "control-proxy.deployment") -}}
{{- define "control-proxy.deployment" -}}
metadata:
  labels:
    app.kubernetes.io/component: control-proxy
  name: control-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: control-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: control-proxy
    spec:
      containers:
      -
{{ include "agwc.container" (list . "control-proxy.container")}}
{{- end -}}
{{- define "control-proxy.container" -}}
name: control-proxy
args:
  - sh
  - -c
  - while [ ! -f /var/opt/magma/certs/gateway.crt ]; do sleep 1; done && /usr/local/bin/generate_nghttpx_config.py &&
    /usr/bin/env nghttpx --conf /var/opt/magma/tmp/nghttpx.conf /var/opt/magma/certs/controller.key /var/opt/magma/certs/controller.crt
image: "{{ .Values.image.repository }}/agw_gateway_python{{ .Values.image.arch}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- end -}}
