---
#
## Copyright (c) 2016-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the BSD-style license found in the
## LICENSE file in the root directory of this source tree. An additional grant
## of patent rights can be found in the PATENTS file in the same directory.

# log_level is set in mconfig. it can be overridden here
fluent_bit_port: 5170
tcp_timeout: 5
event_registry:
  mock_subscriber_event:
    module: orc8r
    filename: mock_event_definitions.v1.yml
  session_created:
    module: lte
    filename: session_manager_events.v1.yml
  session_terminated:
    module: lte
    filename: session_manager_events.v1.yml
  deleted_stored_mconfig:
     module: orc8r
     filename: magmad_events.v1.yml
  updated_stored_mconfig:
    module: orc8r
    filename: magmad_events.v1.yml
  processed_updates:
    module: orc8r
    filename: magmad_events.v1.yml
  restarted_services:
    module: orc8r
    filename: magmad_events.v1.yml
  established_sync_rpc_stream:
    module: orc8r
    filename: magmad_events.v1.yml
  disconnected_sync_rpc_stream:
    module: orc8r
    filename: magmad_events.v1.yml
  attach_success:
    module: lte
    filename: mme_events.v1.yml
  detach_success:
    module: lte
    filename: mme_events.v1.yml
  s1_setup_success:
    module: lte
    filename: mme_events.v1.yml
