# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
appVersion: "1.0"
description: Helm chart for the Magma Orchestrator
name: orc8r
version: 1.5.24
home: https://www.magmacore.org
sources:
  - https://github.com/magma/magma
keywords:
  - magma
  - orc8r

dependencies:
  - name: certs
    version: 0.1.0
    repository: ""
    condition: certs.create
  - name: secrets
    version: 0.1.10
    repository: ""
    condition: secrets.create
  - name: metrics
    version: 1.4.24
    repository: ""
    condition: metrics.enabled
  - name: nms
    version: 0.1.12
    repository: ""
    condition: nms.enabled
  - name: logging
    version: 0.1.10
    repository: ""
    condition: logging.enabled
  - name: orc8rlib
    version: 0.1.4
    repository: file://../orc8rlib
