# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

dependencies:
  - name: secrets
    version: 0.1.3
    repository: ""
    condition: secrets.create
  - name: metrics
    version: 1.3.1
    repository: ""
    condition: metrics.enabled
  - name: nms
    version: 0.1.0
    repository: ""
    condition: nms.enabled
  - name: logging
    version: 0.1.9
    repository: ""
    condition: logging.enabled
