# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

version: "3.7"

services:
  proxy:
    image: "${DOCKER_REGISTRY}/proxy:${IMAGE_VERSION}"
    volumes:
      - /var/opt/magma/certs:/var/opt/magma/certs
      - /var/opt/magma/envdir:/var/opt/magma/envdir
    ports:
      - "9443:9443"  # API/controller port
      - "9444:9444"  # Bootstrapper port
      # TODO: remove the following bindings after migrating
      # the existing load balancers
      - "443:9443"  # API/controller port
      - "8443:9444"  # Bootstrapper port
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  metricsd:
    # Run metricsd to publish disk metrics
    image: "${DOCKER_REGISTRY}/controller:${IMAGE_VERSION}"
    volumes:
      - /var/opt/magma/configs:/var/opt/magma/configs
      - /var/opt/magma/envdir:/var/opt/magma/envdir
    command: /usr/bin/envdir /var/opt/magma/envdir /var/opt/magma/bin/metricsd -logtostderr=true -v=0
    restart: always