---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

profile: "prometheus"

prometheusPushAddresses:
  - "http://prometheus-cache:9091/metrics"

prometheusQueryAddress: "http://prometheus:9090"

alertmanagerApiURL: "http://alertmanager:9093/api/v2/alerts"
prometheusConfigServiceURL: "http://prometheus-configurer:9100"
alertmanagerConfigServiceURL: "http://alertmanager-configurer:9101"
