---
# Copyright (c) 2019-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

services:
  streamer:
    host: "localhost"
    port: 9082

  metricsd:
    host: "localhost"
    port: 9084

  checkind:
    host: "localhost"
    port: 9085

  certifier:
    host: "localhost"
    port: 9086

  upgrade:
    host: "localhost"
    port: 9087

  bootstrapper:
    host: "localhost"
    port: 9088

  accessd:
    host: "localhost"
    port: 9091

  magmad:
    host: "localhost"
    port: 9092

  obsidian:
    host: "localhost"
    port: 9093

  logger:
    host: "localhost"
    port: 9095

  dispatcher:
    host: "localhost"
    port: 9096

  config:
    host: "localhost"
    port: 9099

  directoryd:
    host: "localhost"
    port: 9100

  mconfig_streamer:
    host: "localhost"
    port: 9105

  materializer:
    host: "localhost"
    port: 9106
