- name: metallb | Ensure stable helm repo
  command: helm repo add stable https://charts.helm.sh/stable/

- name: metallb | Update repo metadata
  command: helm repo update

- name: mariadb | Ensure namespace
  command: kubectl create ns {{ infra_namespace }}
  failed_when: false

- name: metallb | Ensure charts dir
  file:
    path: "{{ charts_dir }}"
    state: directory
    recurse: yes

- name: metallb | Template out helm chart values
  template:
    src: metallb-values.yaml.j2
    dest: "{{ charts_dir }}/{{ item }}-values.yaml"
  with_items:
    - metallb

- name: metallb | Install/upgrade helm charts
  command: helm upgrade --install -n {{ infra_namespace }} {{ item }} stable/{{ item }} -f {{ charts_dir }}/{{ item }}-values.yaml
  with_items:
    - metallb
