---
- name: Set up Magma test environment on a local machine
  hosts: test
  become: yes

  vars:
    magma_root: /home/{{ ansible_user }}/magma
    preburn: false
    full_provision: true

  roles:
    - role: apt_cache
      vars:
        distribution: "stretch"
        oai_build: "{{ c_build }}/core/oai"
        repo: "dev"
    - role: pkgrepo_fb
    - role: python_dev
    - role: dev_common
      vars:
        c_build: /home/{{ ansible_user }}/build/c
        go_build: /home/{{ ansible_user }}/go/bin/
    - role: magma_test
      become: no
