language: go

go:
        - "1.4"
        - "1.5"
        - "1.6"
        - "1.7"
        - "1.8"
        - "1.9"
        - "1.10"
        - "1.11"

script:
        - go test -v -race -cover -bench . ./diam/...

install:
        - go get -v golang.org/x/net/context
        - go get -v golang.org/x/tools/cmd/cover
        - go get -v github.com/ishidawataru/sctp
