---
swagger: "2.0"

magma-gen-meta:
  go-package: magma/dp/could/go/services/dp/obsidian/models
  dependencies:
    - 'orc8r/cloud/go/models/swagger-common.yml'
  temp-gen-filename: dp-swagger.yml
  output-dir: dp/cloud/go/services/dp/obsidian

info:
  title: Domain Proxy Management
  description: Domain Proxy REST APIs
  version: 1.0.0
basePath: /magma/v1

definitions:
  capabilities:
    properties:
      max_ibw_mhz:
        description: this is the maximum allowed difference in MHz between leftmost end of leftmost channel and rightmost end of rightmost channel used by a Base Station (eNB)
        type: integer
        x-nullable: false
        maximum: 150
        multipleOf: 5
      min_power:
        description: min tx power available on cbsd
        type: number
      max_power:
        description: max tx power available on cbsd
        example: 30
        type: number
      number_of_antennas:
        minimum: 1
        example: 2
        type: integer
        x-nullable: false
    required:
      - min_power
      - max_power
      - number_of_antennas
      - max_ibw_mhz
    type: object
    x-nullable: false
  cbsd:
    type: object
    properties:
      capabilities:
        $ref: '#/definitions/capabilities'
      carrier_aggregation_enabled:
        description: this flag controls eNB behavior, should multiple grants be used for Carrier Aggregation, or one for Single Carrier
        type: boolean
        x-nullable: false
      cbsd_id:
        description: id of cbsd in SAS
        example: some_cbsd_id
        type: string
        x-nullable: false
      cbsd_category:
        description: is the radio type A (only) or B (also applies to A/B type radios)
        enum:
          - a
          - b
        type: string
        x-nullable: false
      desired_state:
        description: desired state of cbsd in SAS
        enum:
          - unregistered
          - registered
        type: string
        x-nullable: false
      fcc_id:
        example: some_fcc_id
        minLength: 1
        type: string
        x-nullable: false
      frequency_preferences:
        $ref: '#/definitions/frequency_preferences'
      grants:
        items:
          $ref: '#/definitions/grant'
        type: array
      grant_redundancy:
        description: tells Domain Proxy how many grants from SAS should be maintained. If enabled, Domain Proxy will try to maintain at least 2 grants, if disabled, Domain Proxy will maintain only 1 grant
        type: boolean
        x-nullable: false
      id:
        description: database id of cbsd
        type: integer
        x-nullable: false
      installation_param:
        $ref: '#/definitions/installation_param'
        x-nullable: false
      is_active:
        description: false if cbsd have not contacted DP for certain amount of time
        type: boolean
        x-nullable: false
      serial_number:
        example: some_serial_number
        minLength: 1
        type: string
        x-nullable: false
      single_step_enabled:
        description: should the CBSD be registered in a single-step mode
        type: boolean
        x-nullable: false
      state:
        description: state of cbsd in SAS
        enum:
          - unregistered
          - registered
        type: string
        x-nullable: false
      user_id:
        example: some_user_id
        minLength: 1
        type: string
        x-nullable: false
    required:
      - capabilities
      - desired_state
      - fcc_id
      - frequency_preferences
      - id
      - is_active
      - serial_number
      - state
      - user_id
      - single_step_enabled
      - cbsd_category
      - installation_param
      - carrier_aggregation_enabled
      - grant_redundancy
  frequency_preferences:
    properties:
      bandwidth_mhz:
        description: preferred bandwidth of sas channel
        enum:
          - 5
          - 10
          - 15
          - 20
        type: integer
        x-nullable: false
      frequencies_mhz:
        description: list of preferred frequencies (midpoints) of sas channels
        items:
          maximum: 3695
          minimum: 3555
          multipleOf: 5
          type: integer
        type: array
    required:
      - bandwidth_mhz
      - frequencies_mhz
    type: object
    x-nullable: false
  grant:
    properties:
      bandwidth_mhz:
        example: 20
        type: integer
        x-nullable: false
      frequency_mhz:
        example: 3600
        maximum: 3700
        minimum: 3550
        type: integer
        x-nullable: false
      grant_expire_time:
        format: date-time
        type: string
      max_eirp:
        maximum: 37
        minimum: -137
        type: number
        x-nullable: false
      state:
        enum:
          - granted
          - authorized
          - unsync
        type: string
        x-nullable: false
      transmit_expire_time:
        format: date-time
        type: string
    required:
      - bandwidth_mhz
      - frequency_mhz
      - max_eirp
      - state
  installation_param:
    properties:
      antenna_gain:
        example: 15
        type: number
        x-nullable: true
      height_m:
        description: the CBSD antenna height in meters
        type: number
        x-nullable: true
      height_type:
        description: AGL - relative to the ground level. AMSL - relative to the mean sea level
        type: string
        enum:
          - agl
          - amsl
        x-nullable: true
      indoor_deployment:
        description: true if the CBSD is located indoors
        type: boolean
        x-nullable: true
      latitude_deg:
        description: latitude coordinates of the radio in degrees
        type: number
        x-nullable: true
      longitude_deg:
        description: longitude coordinates of the radio in degrees
        type: number
        x-nullable: true
    type: object
    x-nullable: false
  log:
    properties:
      body:
        description: Body of log
        example: '{[{"registrationRequest":{"cbsdSerialNumber":"some_serial_number"}}]}'
        x-nullable: false
        type: string
      fcc_id:
        description: Fcc Id of cbsd involved in log
        example: some_fcc_id
        x-nullable: false
        type: string
      serial_number:
        description: Serial number of cbsd involved in log
        example: some_serial_number
        x-nullable: false
        type: string
      time:
        description: Datetime of log
        format: date-time
        x-nullable: false
        type: string
      type:
        description: Type of log
        x-nullable: false
        type: string
      from:
        description: log origin
        x-nullable: false
        enum:
          - SAS
          - DP
          - CBSD
        type: string
      to:
        description: log destination
        x-nullable: false
        enum:
          - SAS
          - DP
          - CBSD
        type: string
    required:
      - body
      - fcc_id
      - serial_number
      - time
      - type
      - from
      - to
    type: object
  mutable_cbsd:
    type: object
    properties:
      capabilities:
        $ref: '#/definitions/capabilities'
      carrier_aggregation_enabled:
        description: this flag controls eNB behavior, should multiple grants be used for Carrier Aggregation, or one for Single Carrier
        type: boolean
      cbsd_category:
        description: is the radio type A (only) or B (also applies to A/B type radios)
        enum:
          - a
          - b
        type: string
        default: b
        x-nullable: false
      desired_state:
        description: desired state of cbsd in SAS
        enum:
          - unregistered
          - registered
        type: string
        x-nullable: false
      fcc_id:
        example: some_fcc_id
        minLength: 1
        type: string
        x-nullable: false
      frequency_preferences:
        $ref: '#/definitions/frequency_preferences'
      grant_redundancy:
        description: Tells Domain Proxy how many grants from SAS should be maintained. If enabled, Domain Proxy will try to maintain at least 2 grants, if disabled, Domain Proxy will maintain only 1 grant
        type: boolean
      installation_param:
        $ref: '#/definitions/mutable_installation_param'
      serial_number:
        example: some_serial_number
        minLength: 1
        type: string
        x-nullable: false
      user_id:
        example: some_user_id
        minLength: 1
        type: string
        x-nullable: false
      single_step_enabled:
        description: should the CBSD be registered in a single-step mode
        type: boolean
    required:
      - capabilities
      - desired_state
      - fcc_id
      - frequency_preferences
      - serial_number
      - user_id
      - single_step_enabled
      - cbsd_category
      - carrier_aggregation_enabled
      - grant_redundancy
  mutable_installation_param:
    properties:
      antenna_gain:
        example: 15
        type: number
        x-nullable: true
    type: object
    x-nullable: false
  paginated_cbsds:
    description: Page of cbsds
    properties:
      cbsds:
        items:
          $ref: '#/definitions/cbsd'
        type: array
      total_count:
        description: Total number of cbsds
        example: 10
        type: integer
        x-nullable: false
    required:
      - cbsds
      - total_count
  paginated_logs:
    description: Page of logs
    properties:
      logs:
        items:
          $ref: '#/definitions/log'
        type: array
      total_count:
        description: Total number of logs
        example: 10
        x-nullable: false
        type: integer
    required:
      - logs
      - total_count
tags:
  - description: API for CBSDs
    name: cbsds
  - description: API for retrieving logs
    name: logs
paths:
  /dp/{network_id}/cbsds:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - description: serial number of cbsd
          in: query
          name: serial_number
          required: false
          type: string
      responses:
        '200':
          description: All CBSDs in LTE network
          schema:
            $ref: '#/definitions/paginated_cbsds'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: List all CBSDs in LTE network
      tags:
        - cbsds
    post:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - description: CBSD
          in: body
          name: cbsd
          required: true
          schema:
            $ref: '#/definitions/mutable_cbsd'
      responses:
        '201':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Create new cbsd
      tags:
        - cbsds
  /dp/{network_id}/cbsds/{cbsd_id}:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '200':
          description: CBSD
          schema:
            $ref: '#/definitions/cbsd'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Retrieve CBSD from LTE network
      tags:
        - cbsds
    put:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
        - description: CBSD
          in: body
          name: cbsd
          required: true
          schema:
            $ref: '#/definitions/mutable_cbsd'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Update CBSD in LTE network
      tags:
        - cbsds
    delete:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Delete CBSD from LTE network
      tags:
        - cbsds
  /dp/{network_id}/cbsds/{cbsd_id}/deregister:
    post:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Force deregistration in SAS of given CBSD
      tags:
        - cbsds
  /dp/{network_id}/cbsds/{cbsd_id}/relinquish:
    post:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Force relinquish all grants in SAS of given CBSD
      tags:
        - cbsds
  /dp/{network_id}/logs:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - description: start datetime of log
          format: date-time
          in: query
          name: begin
          required: false
          type: string
        - description: end datatime of log
          format: date-time
          in: query
          name: end
          required: false
          type: string
        - description: serial number of cbsd
          in: query
          minLength: 1
          maxLength: 64
          name: serial_number
          required: false
          type: string
        - description: fcc id of cbsd
          in: query
          minLength: 1
          maxLength: 19
          name: fcc_id
          required: false
          type: string
        - description: log type
          in: query
          name: type
          required: false
          type: string
        - description: response code (only applicable for SAS responses)
          in: query
          name: response_code
          required: false
          type: integer
        - description: log origin
          in: query
          name: from
          required: false
          type: string
          enum:
            - SAS
            - DP
            - CBSD
        - description: log destination
          in: query
          name: to
          required: false
          type: string
          enum:
            - SAS
            - DP
            - CBSD
      responses:
        '200':
          description: List of messages between ENODEBD and DP and between DP and SAS
          schema:
            $ref: '#/definitions/paginated_logs'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: List messages between ENODEBD and DP and between DP and SAS ordered by time
      tags:
        - logs

parameters:
  cbsd_id:
    description: CBSD ID
    in: path
    name: cbsd_id
    required: true
    type: integer
  offset:
    description: Start index for pagination
    in: query
    minimum: 1
    name: offset
    required: false
    type: integer
  limit:
    description: Number of record to return
    in: query
    minimum: 1
    name: limit
    required: false
    type: integer
