---
swagger: "2.0"

magma-gen-meta:
  go-package: magma/dp/could/go/services/dp/obsidian/models
  dependencies:
    - 'orc8r/cloud/go/models/swagger-common.yml'
  temp-gen-filename: dp-swagger.yml
  output-dir: dp/cloud/go/services/dp/obsidian

info:
  title: Domain Proxy Management
  description: Domain Proxy REST APIs
  version: 1.0.0
basePath: /magma/v1

definitions:
  capabilities:
    properties:
      min_power:
        description: min tx power available on cbsd
        type: number
      max_power:
        description: max tx power available on cbsd
        example: 30
        type: number
      number_of_antennas:
        minimum: 1
        example: 2
        type: integer
      antenna_gain:
        example: 15
        type: number
    type: object
    required:
      - antenna_gain
      - min_power
      - max_power
      - number_of_antennas
  cbsd:
    type: object
    properties:
      capabilities:
        $ref: '#/definitions/capabilities'
      fcc_id:
        example: some_fcc_id
        minLength: 1
        type: string
      serial_number:
        example: some_serial_number
        minLength: 1
        type: string
      user_id:
        example: some_user_id
        minLength: 1
        type: string
      cbsd_id:
        description: id of cbsd in SAS
        example: some_cbsd_id
        readOnly: true
        type: string
      grant:
        $ref: '#/definitions/grant'
      id:
        description: database id of cbsd
        readOnly: true
        type: integer
      is_active:
        description: false if cbsd have not contcated DP for certain amount of time
        readOnly: true
        type: boolean
      state:
        description: state of cbsd in SAS
        enum:
          - unregistered
          - registered
        readOnly: true
        type: string
    required:
      - fcc_id
      - serial_number
      - user_id
      - capabilities
  grant:
    properties:
      bandwidth_mhz:
        example: 20
        type: integer
      frequency_mhz:
        example: 3600
        maximum: 3700
        minimum: 3550
        type: integer
      grant_expire_time:
        format: date-time
        type: string
      max_eirp:
        maximum: 37
        minimum: -137
        type: number
      state:
        enum:
          - granted
          - guthorized
        type: string
      transmit_expire_time:
        format: date-time
        type: string
    readOnly: true
  components:
    enum: &components
      - SAS
      - DP
      - CBSD
    type: string
  message:
    properties:
      body:
        description: Body of message
        example: '{[{"registrationRequest":{"cbsdSerialNumber":"some_serial_number"}}]}'
        readOnly: true
        type: string
      fcc_id:
        description: Fcc Id of cbsd involved in message
        example: some_fcc_id
        readOnly: true
        type: string
      serial_number:
        description: Serial number of cbsd involved in message
        example: some_serial_number
        readOnly: true
        type: string
      time:
        description: Datetime of message
        format: date-time
        readOnly: true
        type: string
      type:
        description: Type of message
        readOnly: true
        type: string
      from:
        description: message origin
        readOnly: true
        enum: *components
        type: string
      to:
        description: message destination
        readOnly: true
        enum: *components
        type: string
    type: object
tags:
  - description: API for retrieving logs
    name: logs
  - description: API for CBSDs
    name: cbsds
paths:
  /dp/{network_id}/logs:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
        - description: start datetime of messages
          format: date-time
          in: query
          name: begin
          required: false
          type: string
        - description: end datatime of messages
          format: date-time
          in: query
          name: end
          required: false
          type: string
        - description: serial number of cbsd
          in: query
          minLength: 1
          maxLength: 64
          name: serial_number
          required: false
          type: string
        - description: fcc id of cbsd
          in: query
          minLength: 1
          maxLength: 19
          name: fcc_id
          required: false
          type: string
        - description: message type
          in: query
          name: type
          required: false
          type: string
        - description: response code (only applicable for SAS responses)
          in: query
          name: response_code
          required: false
          type: integer
        - description: message origin
          in: query
          name: from
          required: false
          type: string
          enum: *components
        - description: message destination
          in: query
          name: to
          required: false
          type: string
          enum: *components
      responses:
        '200':
          description: Messages between DP and SAS
          schema:
            items:
              $ref: '#/definitions/message'
            type: array
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: List messages between DP and SAS ordered by time
      tags:
        - logs
  /dp/{network_id}/cbsds:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          description: All CBSDs in LTE network
          schema:
            items:
              $ref: '#/definitions/cbsd'
            type: array
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: List all CBSDs in LTE network
      tags:
        - cbsds
    post:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - description: CBSD
          in: body
          name: cbsd
          required: true
          schema:
            $ref: '#/definitions/cbsd'
      responses:
        '201':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Create new cbsd
      tags:
        - cbsds
  /dp/{network_id}/cbsds/{cbsd_id}:
    get:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '200':
          description: CBSD
          schema:
            $ref: '#/definitions/cbsd'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Retrieve CBSD from LTE network
      tags:
        - cbsds
    put:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
        - description: CBSD
          in: body
          name: cbsd
          required: true
          schema:
            $ref: '#/definitions/cbsd'
      responses:
        '201':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Update CBSD in LTE network
      tags:
        - cbsds
    delete:
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: '#/parameters/cbsd_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
      summary: Delete CBSD from LTE network
      tags:
        - cbsds

parameters:
  cbsd_id:
    description: CBSD ID
    in: path
    name: cbsd_id
    required: true
    type: integer
  offset:
    description: Start index for pagination
    in: query
    minimum: 1
    name: offset
    required: false
    type: integer
  limit:
    description: Number of record to return
    in: query
    minimum: 1
    name: limit
    required: false
    type: integer
