---
swagger: '2.0'
info:
  title: Subscriberdb Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

tags:
  - name: Subscribers
    description: Operations about subscribers

paths:
  /networks/{network_id}/subscribers:
    get:
      summary: List subscribers in the network
      tags:
      - Subscribers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: query
        name: fields
        type: string
        description: Which fields to return (ids or all)
        required: false
      responses:
        '200':
          description: List of subscriber ids
          schema:
            type: array
            items:
              $ref: './swagger-common.yml#/definitions/subscriber_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new subscriber to the network
      tags:
      - Subscribers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: subscriber
        description: Subscriber object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/subscriber'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/subscribers/{subscriber_id}:
    get:
      summary: Retrieve the subscriber info
      tags:
      - Subscribers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Subscriber Info
          schema:
            $ref: '#/definitions/subscriber'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify subscriber info
      tags:
      - Subscribers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/subscriber_id'
      - in: body
        name: subscriber
        description: Subscriber Info
        required: true
        schema:
          $ref: '#/definitions/subscriber'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Remove a subscriber from the network
      tags:
      - Subscribers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/subscriber_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  subscriber_id:
    type: string
    pattern: '^(IMSI\d{10,15})$'
    example: IMSI208950000000010
  lte_subscription:
    type: object
    required:
    - auth_key
    properties:
      state:
        type: string
        enum:
        - INACTIVE
        - ACTIVE
        default: INACTIVE
        x-nullable: false
      auth_algo:
        type: string
        enum:
        - MILENAGE
        default: MILENAGE
        x-nullable: false
      auth_key:
        type: string
        format: byte # auth_key is encoded in base64
        x-nullable: true
        example: "AAAAAAAAAAAAAAAAAAAAAA=="
      auth_opc:
        type: string
        format: byte # auth_opc is encoded in base64
        x-nullable: true
        example: 'AAECAwQFBgcICQoLDA0ODw=='
      sub_profile:
        type: string
        minLength: 1
        example: 'default'
  subscriber:
    type: object
    properties:
      id:
        $ref: './swagger-common.yml#/definitions/subscriber_id'
        x-nullable: false
        x-go-custom-tag: 'magma_alt_name:"Id"'
      lte:
        $ref: '#/definitions/lte_subscription'
  # this is a read-only object
  subscriber_state:
    type: object
    properties:
      lte_auth_next_seq:
        type: integer
        format: uint64
        x-nullable: false
      tgpp_aaa_server_name:
        type: string
        x-nullable: false
      tgpp_aaa_server_registered:
        type: boolean
        example: false
