---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- name: Copy preferences file for Magma's pkg repo
  copy: src=magma-preferences dest=/etc/apt/preferences.d/magma-preferences

- name: Install OVS Dependencies for Ubuntu
  apt:
    state: present
    update_cache: yes
    pkg:
      - graphviz
      - autoconf
      - automake
      - bzip2
      - debhelper
      - dh-autoreconf
      - libssl-dev
      - libtool
      - openssl
      - procps
      - python-all
      - python-twisted-conch
      - python-zope.interface
      - python-six
      - build-essential
      - fakeroot

- name: Install patched OVS v2.12.0 from Magma's pkgrepo
  apt:
     state: present
     pkg:
       - libopenvswitch
       - openvswitch-common
       - openvswitch-switch
       - python-openvswitch
       - openvswitch-datapath-dkms

- name: Start OVS
  service:
    name: openvswitch-switch
    state: started
    enabled: yes
    use: service
  become: true

- name: Ensure OVS switch will not auto-upgrade
  action: shell apt-mark hold openvswitch-switch
