apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: kubevirt
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-conf-config",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "br0",
                "ipam": {}
            },
            {
                "type": "tuning"
            }
        ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
  namespace: kubevirt
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-conf-1-config",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "br1",
                "ipam": {}
            },
            {
                "type": "tuning"
            }
        ]
    }
