{{/*
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
*/}}

{{- if .Values.nginx.create }}
{{- $envAll := . }}
{{ $serviceType := .Values.nginx.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
{{ tuple $envAll "nms" "nginx" | include "nms.labels" | indent 4 }}
  {{- if .Values.nginx.service.annotations }}
  annotations:
{{ with .Values.nginx.service.annotations }}{{ toYaml . | indent 4 }}{{ end }}
  {{- end }}
spec:
  selector:
{{ tuple $envAll "nms" "nginx" | include "nms.selector-labels" | indent 4 }}
  type: "{{ .Values.nginx.service.type }}"
  ports:
  - name: https
    port: {{ .Values.nginx.service.https.port }}
    targetPort: {{ .Values.nginx.service.https.targetPort }}
    protocol: TCP
    {{- if eq $serviceType "NodePort" }}
    {{- if .Values.nginx.service.https.nodePort }}
    nodePort: {{ .Values.nginx.service.https.nodePort }}
    {{- end -}}
    {{- end -}}
{{- if eq $serviceType "LoadBalancer" }}
  {{- if .Values.nginx.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.nginx.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.nginx.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.nginx.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
{{- end -}}
