---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- name: Create OVS bridge cwag_br0 and GRE tunnel gre0
  become: true
  script: create_gre_tunnel.sh

- name: Create OVS bridge uplink_br0 and add peer patch port to connect it to cwag_br0
  become: true
  script: setup_default_uplink_bridge.sh

- name: Setup internal port and interface for DPI
  become: true
  script: setup_dpi_port.sh

- name: Enable IP forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Add static IP to cwag_br0
  become: true
  copy:
    src: 99-ovscfg.yaml
    dest: /etc/netplan

- name: Apply netplan for OVS cwag_br0 interface
  become: true
  shell: netplan apply
