version: "3.7"

services:
  docusaurus:
    volumes:
      - ./../docusaurus:/app/website
      - ./../readmes:/app/readmes
    ports:
      - 3000:3000/tcp
      - 35729:35729/tcp
    image: magma_docusaurus
    command: bash -c 'npm install && npm start -- --host 0.0.0.0'
