version: "3.7"

# Standard logging for each service
x-logging: &logging_anchor
  driver: "json-file"
  options:
    max-size: "10mb"
    max-file: "10"

# Standard volumes mounted
x-standard-volumes: &volumes_anchor
  - ${ROOTCA_PATH}:/var/opt/magma/certs/rootCA.pem
  - ${CERTS_VOLUME}:/var/opt/magma/certs
  - ${CONFIGS_OVERRIDE_VOLUME}:/var/opt/magma/configs
  - ${CONFIGS_DEFAULT_VOLUME}:/etc/magma
  - ${CONFIGS_TEMPLATES_PATH}:/etc/magma/templates
  - ${CONTROL_PROXY_PATH}:/etc/magma/control_proxy.yml
  - /etc/snowflake:/etc/snowflake

x-generic-service: &service
  volumes: *volumes_anchor
  logging: *logging_anchor
  restart: always
  network_mode: host

# Generic python anchor to avoid repetition for lte c services
x-lte-cservice: &dpiservice
  <<: *service
  image: ${DOCKER_REGISTRY}gateway_dpid:${IMAGE_VERSION}

services:
  dpid:
    <<: *dpiservice
    container_name: dpid
    environment:
      - DPI_LICENSE=${DPI_LICENSE}
    command: /usr/local/bin/dpid
