# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
---
- name: Set up Carrier WiFi Access Gateway for development
  hosts: cwag
  become: yes
  vars:
    - magma_root: /home/{{ ansible_user }}/magma
    - user: vagrant
    - full_provision: true
  roles:
    - role: ovs
    - role: golang

  tasks:
    # Only run installation for docker
    - include_role:
        name: docker
        tasks_from: install

    - name: Create snowflake file
      copy:
        content: ""
        dest: /etc/snowflake

    # Required by some go libraries
    - name: Install bzr dependency
      apt:
        name: bzr
        state: present

