########################################
# Golang provisioning
########################################

- name: Create gobin directories
  become: yes
  become_user: '{{ user }}'
  file:
    path: '{{ item }}'
    state: directory
  with_items: '{{ gobin.split(":") }}'

- name: Remove Old Golang
  file: path="{{ go_install_path }}/go/" state=absent

- name: Download Golang
  get_url:
    url: "https://dl.google.com/go/{{ golang_tar }}"
    dest: "/home/{{ user }}/{{ golang_tar }}"
    checksum: "{{ golang_tar_checksum }}"
  when: full_provision

- name: Extract Golang
  unarchive:
    src: /home/{{ user }}/{{ golang_tar }}
    dest: "{{ go_install_path }}"
    remote_src: yes
  when: full_provision

- name: Remove Golang tar
  file: path=/home/{{ user }}/{{ golang_tar }} state=absent
  when: full_provision

- name: Set Go environment vars in profile
  tags: magma-cloud-dev
  lineinfile:
    dest: "/home/{{ user }}/.profile"
    state: present
    line: "{{ item }}"
  with_items:
    - export GOPATH={{ gopath }}
    - export GOBIN={{ gobin }}
    - export GOPROXY={{ goproxy }}
    - export PATH=$PATH:{{ go_bin_path }}:{{ makebin }}

- name: Install protoc-gen-go
  become: yes
  become_user: '{{ user }}'
  environment:
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gobin }}"
    PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
  command: go get -u github.com/golang/protobuf/protoc-gen-go
  when: full_provision

- name: Install golint
  become: yes
  become_user: '{{ user }}'
  environment:
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gobin }}"
    PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
  command: go get -u golang.org/x/lint/golint
  when: full_provision

- name: Install gotestsum
  become: yes
  become_user: '{{ user }}'
  environment:
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gobin }}"
    PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
  command: go get -u gotest.tools/gotestsum
  when: full_provision
