---
swagger: '2.0'
info:
  title: Alertmanager Configurer Model Definitions and Paths
  description: Alertmanager Configurer REST APIs
  version: 1.0.0

paths:
  /receiver:
    post:
      summary: Create new alert receiver
      tags:
        - Receivers
      parameters:
        - $ref: '#/parameters/tenant_id'
        - in: body
          name: receiver_config
          description: Alert receiver that is to be added
          required: true
          schema:
            $ref: '#/definitions/receiver_config'
      responses:
        '201':
          description: Created
        default:
          $ref: '#/responses/UnexpectedError'
    get:
      summary: Retrieve alert receivers
      tags:
        - Receivers
      parameters:
        - $ref: '#/parameters/tenant_id'
      responses:
        '200':
          description: List of alert receivers
          schema:
            type: array
            items:
              $ref: '#/definitions/receiver_config'
        default:
          $ref: '#/responses/UnexpectedError'
    delete:
      summary: Delete alert receiver
      tags:
        - Receivers
      parameters:
        - $ref: '#/parameters/tenant_id'
        - in: query
          name: receiver
          description: Receiver name to be deleted
          required: true
          type: string
      responses:
        '200':
          description: Deleted
        default:
          $ref: '#/responses/UnexpectedError'
    put:
      summary: Update existing alert receiver
      tags:
        - Receivers
      parameters:
        - $ref: '#/parameters/tenant_id'
        - in: query
          name: receiver_name
          description: Name of receiver to be updated
          required: true
          type: string
        - in: body
          name: receiver_config
          description: Updated alert receiver
          required: true
          schema:
            $ref: '#/definitions/receiver_config'
      responses:
        '200':
          description: Updated
        default:
          $ref: '#/responses/UnexpectedError'

  /route:
    get:
      summary: Retrieve alert routing tree
      tags:
        - Routes
      parameters:
        - $ref: '#/parameters/tenant_id'
      responses:
        '200':
          description: Alerting tree
          schema:
            $ref: '#/definitions/routing_tree'
    post:
      summary: Modify alert routing tree
      tags:
        - Routes
      parameters:
        - $ref: '#/parameters/tenant_id'
        - in: body
          name: route
          description: Alert routing tree to be used
          required: true
          schema:
            $ref: '#/definitions/routing_tree'
      responses:
        '200':
          description: OK
        default:
          $ref: '#/responses/UnexpectedError'

parameters:
  tenant_id:
    description: Tenant ID
    in: query
    name: tenant_id
    required: false
    type: string

definitions:
  receiver_config:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      slack_configs:
        type: array
        items:
          $ref: '#/definitions/slack_receiver'

  slack_receiver:
    type: object
    required:
      - api_url
    properties:
      api_url:
        type: string
      channel:
        type: string
      username:
        type: string
      color:
        type: string
      title:
        type: string
      pretext:
        type: string
      text:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/slack_field'
      short_fields:
        type: boolean
      footer:
        type: string
      fallback:
        type: string
      callback_id:
        type: string
      icon_emoji:
        type: string
      icon_url:
        type: string
      image_url:
        type: string
      thumb_url:
        type: string
      link_names:
        type: boolean
      actions:
        type: array
        items:
          $ref: '#/definitions/slack_action'

  slack_field:
    type: object
    required:
      - title
      - value
    properties:
      title:
        type: string
      value:
        type: string
      short:
        type: boolean

  slack_action:
    type: object
    required:
      - type
      - text
      - url
    properties:
      type:
        type: string
      text:
        type: string
      url:
        type: string
      style:
        type: string
      name:
        type: string
      value:
        type: string
      confirm:
        $ref: '#/definitions/slack_confirm_field'

  slack_confirm_field:
    type: object
    required:
      - text
      - title
      - ok_text
      - dismiss_text
    properties:
      text:
        type: string
      title:
        type: string
      ok_text:
        type: string
      dismiss_text:
        type: string

  routing_tree:
    type: object
    required:
      - receiver
    properties:
      receiver:
        type: string
      group_by:
        type: array
        items:
          type: string
      match:
        type: object
        properties:
          label:
            type: string
          value:
            type: string
      match_re:
        type: object
        properties:
          label:
            type: string
          value:
            type: string
      continue:
        type: boolean
      routes:
        type: array
        items:
          $ref: '#/definitions/routing_tree'
      group_wait:
        type: string
      group_interval:
        type: string
      repeat_interval:
        type: string

  error:
    type: object
    required:
      - message
    properties:
      message:
        example: Error string
        type: string

responses:
  UnexpectedError:
    description: Unexpected Error
    schema:
      $ref: '#/definitions/error'
