# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

apiVersion: "1.0"
description: Magma Carrier Gateway
name: cwf
version: 0.1.7
home: https://github.com/facebookincubator/magma
sources:
  - https://github.com/facebookincubator/magma
keywords:
  - magma
  - cwf
