# Provides all dependent services

version: '3.6'

services:
  mariadb:
    image: mariadb:10.4.12
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nms
      MYSQL_USER: nms
      MYSQL_PASSWORD: password
    restart: on-failure
    healthcheck:
      test: mysqladmin ping -p12345

  nginx-proxy:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/docker_ssl_proxy:/etc/nginx/conf.d
    depends_on:
      - magmalte

  magmalte:
    build:
      context: ../..
      dockerfile: fbcnms-projects/magmalte/Dockerfile
    command: "/usr/local/bin/wait-for-it.sh -s -t 30 mariadb:3306 -- yarn run start:dev"
    volumes:
      - ../../fbcnms-packages:/usr/src/fbcnms-packages
      - ../../fbcnms-projects/magmalte/app:/usr/src/fbcnms-projects/magmalte/app
      - ../../fbcnms-projects/magmalte/scripts:/usr/src/fbcnms-projects/magmalte/scripts
      - ../../fbcnms-projects/magmalte/server:/usr/src/fbcnms-projects/magmalte/server
    depends_on:
      - mariadb
    networks:
      - default
      - orc8r_default
    ports:
      - "8081:8081"
    environment:
      API_CERT_FILENAME: /run/secrets/api_cert
      API_PRIVATE_KEY_FILENAME: /run/secrets/api_key
      API_HOST: ${API_HOST:-proxy:9443}
      PORT: 8081
      HOST: 0.0.0.0
      MYSQL_HOST: mariadb
      MYSQL_DB: nms
      MYSQL_USER: nms
      MYSQL_PASS: password
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN:-}
      SEQUELIZE_DIALECT: mariadb
    healthcheck:
      test: curl -If localhost:8081/healthz
    restart: on-failure
    secrets:
      - api_cert
      - api_key

secrets:
  api_cert:
    file: ${API_CERT_FILENAME:-../../../.cache/test_certs/admin_operator.pem}
  api_key:
    file: ${API_PRIVATE_KEY_FILENAME:-../../../.cache/test_certs/admin_operator.key.pem}

networks:
  orc8r_default:
    external: true

volumes:
  mariadb:
