---
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

- name: Copy preferences file for Magma's pkg repo
  copy: src=magma-preferences dest=/etc/apt/preferences.d/magma-preferences

- name: Install OVS Dependencies for Ubuntu
  apt:
    state: present
    update_cache: yes
    pkg:
      - graphviz
      - autoconf
      - automake
      - bzip2
      - debhelper
      - dh-autoreconf
      - libssl-dev
      - libtool
      - openssl
      - procps
      - python-all
      - python-twisted-conch
      - python-zope.interface
      - python-six
      - build-essential
      - fakeroot

- name: Install patched OVS v2.12.0 from Magma's pkgrepo
  apt:
     state: present
     pkg:
       - libopenvswitch
       - openvswitch-common
       - openvswitch-switch
       - python-openvswitch
       - openvswitch-datapath-dkms

- name: Ensure OVS switch will not auto-upgrade
  action: shell apt-mark hold openvswitch-switch

- name: Load the ovs kernel module
  become: true
  script: reload_ovs_kmod.sh
  tags:
      - kernel_module_reload

- name: Start OVS
  service:
    name: openvswitch-switch
    state: started
    enabled: yes
    use: service
  become: true
