- name: nfs-server-provisioner | Ensure stable helm repo
  command: helm repo add stable https://charts.helm.sh/stable/

- name: nfs-server-provisioner | Update repo metadata
  command: helm repo update

- name: nfs-server-provisioner | Ensure namespace
  command: kubectl create ns {{ infra_namespace }}
  failed_when: false

- name: nfs-server-provisioner | Ensure charts dir
  file:
    path: "{{ charts_dir }}"
    state: directory
    recurse: yes

- name: nfs-server-provisioner | Ensure PV path
  file:
    path: "{{ nfs_pv_path }}"
    state: directory
    recurse: yes

- name: nfs-server-provisioner | Template out PV 
  template:
    src: nfs-pv.yaml.j2
    dest: "{{ charts_dir }}/nfs-pv.yaml"

- name: nfs-server-provisioner | Apply NFS PV
  command: kubectl apply -f {{ charts_dir}}/nfs-pv.yaml

- name: nfs-server-provisioner | Template out helm chart values
  template:
    src: nfs-server-provisioner-values.yaml.j2
    dest: "{{ charts_dir }}/{{ item }}-values.yaml"
  with_items:
    - nfs-server-provisioner

- name: nfs-server-provisioner | Install/upgrade helm charts
  command: helm upgrade --install -n {{ infra_namespace }} nfs-server-provisioner stable/{{ item }} -f {{ charts_dir }}/{{ item }}-values.yaml
  with_items:
    - nfs-server-provisioner
