- name: Install Elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: "{{ magma_namespace }}"
    chart_version: "{{ elasticsearch_chart_version }}"
    create_namespace: true
    values:
      replicas: 1
      extraEnvs: 
      - name: discovery.type
        value: single-node
      - name: cluster.initial_master_nodes
        value: null
