# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Config secrets for orc8r module
# TODO: it should be possible to range at the top level and dynamically generate secrets based on subdirectories under .secrets/configs/
{{- if .Values.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-configs-cwf
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
{{- if .Values.secret.configs.enabled }}
{{- range $key, $value := .Values.secret.configs.cwf }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
