# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

{{- if .Values.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-envdir
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
{{- if .Values.secret.envdir }}
{{- range $key, $value := .Values.secret.envdir }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
