{{- if and .Values.create .Values.configuration_controller.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domain-proxy.configuration_controller.fullname" . }}
  labels:
    {{-  include "domain-proxy.configuration_controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.configuration_controller.database }}
  {{- with .Values.configuration_controller.database }}
  {{ if eq .driver "postgres" }}
  SQLALCHEMY_DB_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%d/%s" .user .pass .host (.port | int) .db | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
