# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Create orchestrator secrets.
create: true

# orc8r secret configuration
secret:
  certs:
    enabled: false
  # files:
  #   #Controller Crt
  #   controller.crt: |-
  #     ...
  #     ...
  #   #Controller Key
  #   controller.key: |-
  #     ...
  #     ...
  #   #rootCA
  #   rootca: |-
  #     ...
  #     ...
  #   #NMS Operator Crt
  #   admin_operator.pem: |-
  #     ...
  #     ...
  #   #NMS Operator Key
  #   admin_operator.key.pem: |-
  #     ...
  #     ...
  #   #Fluentd Crt
  #   fluentd.pem: |-
  #     ...
  #     ...
  #   #Fluentd Key
  #   fluentd.key: |-
  #     ...
  #     ...

  # base directory holding config secrets.
  configs:
    enabled: true
    orc8r:
      metricsd: |-
        profile: "prometheus"

        prometheusQueryAddress: "http://orc8r-prometheus:9090"
        prometheusPushAddresses:
          - "http://orc8r-prometheus-cache:9091/metrics"

        alertmanagerApiURL: "http://orc8r-alertmanager:9093/api/v2/alerts"
        prometheusConfigServiceURL: "http://orc8r-config-manager:9100"
        alertmanagerConfigServiceURL: "http://orc8r-config-manager:9101"

  # cwf:
  #   key: value

# base directory holding envdir secrets.
# envdir:
#   key: value

# private docker registry credentials
docker:
  registry:
  username:
  password:
