# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphite
  labels:
    app.kubernetes.io/component: graphite
{{ include "labels" . | indent 4 }}
    {{- with .Values.graphite.service.labels }}
{{ toYaml . | indent 4}}
    {{- end}}
  {{- with .Values.graphite.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: graphite
{{ include "selector-labels" . | indent 4 }}
  type: {{ .Values.graphite.service.type }}
  ports:
{{- range $port := .Values.graphite.service.ports }}
     - name: {{ $port.name }}
       port: {{ $port.port }}
       targetPort: {{ $port.targetPort }}
{{- end }}