{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.prometheusConfigurer.create }}
{{- $serviceName := print .Release.Name "-prometheus-configurer" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: prometheus-configurer
{{ include "metrics.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.prometheusConfigurer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus-configurer
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus-configurer
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.prometheusConfigurer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheusConfigurer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheusConfigurer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      volumes:
        - name: "prometheus-config"
{{ toYaml .Values.metrics.volumes.prometheusConfig.volumeSpec | indent 10 }}

      containers:
        - name: "prometheus-configurer"
          image: {{ required "prometheusConfigurer.image.repository must be provided" .Values.prometheusConfigurer.image.repository }}:{{ .Values.prometheusConfigurer.image.tag }}
          imagePullPolicy: {{ .Values.prometheusConfigurer.image.pullPolicy }}
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: "prometheus-config"
              mountPath: /etc/configs
          args:
            - "-port={{ .Values.prometheusConfigurer.prometheusConfigurerPort }}"
            - "-rules-dir={{ .Values.prometheusConfigurer.rulesDir }}"
            - "-prometheusURL={{ .Values.prometheusConfigurer.prometheusURL }}"
            - "-multitenant=true"
          resources:
{{ toYaml .Values.prometheusConfigurer.resources | indent 12 }}
{{- end }}
