---
swagger: '2.0'
info:
  title: Cellular Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

paths:
  /networks/{network_id}/configs/cellular:
    post:
      summary: Create Network Cellular Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/network_cellular_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Network Cellular Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Retrieved Network Cellular Configs
          schema:
            $ref: '#/definitions/network_cellular_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Network Cellular Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/network_cellular_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Network Cellular Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/configs/cellular:
    post:
      summary: Create Gateway Cellular Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/gateway_cellular_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Gateway Cellular Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Retrieved Gateway Cellular Configs
          schema:
            $ref: '#/definitions/gateway_cellular_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Gateway Cellular Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/gateway_cellular_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Gateway Cellular Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  network_cellular_configs:
    description: Cellular configuration for a network
    type: object
    minLength: 1
    properties:
      ran:
        $ref: '#/definitions/network_ran_configs'
      epc:
        $ref: '#/definitions/network_epc_configs'
      feg_network_id:
        type: string
        example: 'example_feg_network'
  network_ran_configs:
    description: RAN (radio access network) cellular configuration for a network
    type: object
    minLength: 1
    properties:
      earfcndl:
        type: integer
        format: uint32
        example: 44590
      subframe_assignment:
        type: integer
        format: uint32
        example: 2
        maximum: 6
      special_subframe_pattern:
        type: integer
        format: uint32
        example: 7
        maximum: 9
      bandwidth_mhz:
        type: integer
        format: uint32
        example: 20
        enum:
        - 3
        - 5
        - 10
        - 15
        - 20
      fdd_config:
        type: object
        x-go-custom-tag: 'magma_alt_name:"NetworkRANConfigFDDConfig"'
        properties:
          earfcndl:
            type: integer
            format: uint32
            example: 0
          earfcnul:
            type: integer
            format: uint32
            example: 18000
      tdd_config:
        type: object
        x-go-custom-tag: 'magma_alt_name:"NetworkRANConfigTDDConfig"'
        properties:
          earfcndl:
            type: integer
            format: uint32
            example: 44590
          subframe_assignment:
            type: integer
            format: uint32
            example: 2
            maximum: 6
          special_subframe_pattern:
            type: integer
            format: uint32
            example: 7
            maximum: 9
  network_epc_configs:
    description: EPC (evolved packet core) cellular configuration for a network
    type: object
    minLength: 1
    properties:
      mcc:
        type: string
        pattern: '^(\d{3})$'
        example: '001'
      mnc:
        type: string
        pattern: '^(\d{2,3})$'
        example: '01'
      tac:
        type: integer
        format: uint32
        maximum: 65535
        example: 1
      lte_auth_op:
        type: string
        format: byte
        example: EREREREREREREREREREREQ==
      lte_auth_amf:
        type: string
        format: byte
        example: gAA=
      sub_profiles:
        type: object
        additionalProperties:
          type: object
          properties:
            max_ul_bit_rate:
              type: integer
              format: uint64
              example: 100000000
            max_dl_bit_rate:
              type: integer
              format: uint64
              example: 20000000
      default_rule_id:
        type: string
        example: 'default_rule_1'
      relay_enabled:
        type: boolean
        example: false
      network_services:
        description: Configuration for network services. Services will be instantiated in the listed order.
        type: array
        x-omitempty: true
        items:
          type: string
          enum:
          - 'metering'
          - 'dpi'
          - 'policy_enforcement'
        example:
        - 'metering'
        - 'dpi'
        - 'policy_enforcement'

  gateway_cellular_configs:
    description: Cellular configuration for a gateway
    type: object
    minLength: 1
    properties:
      ran:
        $ref: '#/definitions/gateway_ran_configs'
      epc:
        $ref: '#/definitions/gateway_epc_configs'
      non_eps_service:
        $ref: '#/definitions/gateway_non_eps_service_configs'
  gateway_ran_configs:
    description: RAN (radio access network) configuration for a gateway
    type: object
    minLength: 1
    properties:
      pci:
        type: integer
        format: uint32
        maximum: 503
        example: 260
      transmit_enabled:
        type: boolean
        example: true
  gateway_epc_configs:
    description: EPC (evolved packet core) configuration for a gateway
    type: object
    minLength: 1
    required:
    - ip_block
    properties:
      nat_enabled:
        type: boolean
        example: true
      ip_block:
        type: string
        minLength: 5
        maxLength: 49
        example: '192.168.128.0/24'
        x-nullable: false
        x-go-custom-tag: 'magma_alt_name:"IpBlock"'
  gateway_non_eps_service_configs:
    description: Non-EPS service configuration for a gateway
    type: object
    minLength: 1
    properties:
      csfb_mcc:
        type: string
        pattern: '^(\d{3})$'
        example: '001'
      csfb_mnc:
        type: string
        pattern: '^(\d{2,3})$'
        example: '01'
      lac:
        type: integer
        format: uint32
        example: 1
      csfb_rat:
        type: integer
        format: uint32
        enum:
        - 0
        - 1
      arfcn_2g:
        type: array
        items:
          type: integer
          format: uint32
        x-go-custom-tag: 'magma_alt_name:"Arfcn_2G"'
      non_eps_service_control:
        type: integer
        format: uint32
        enum:
        - 0
        - 1
        - 2