---
- name: Register rootCA.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/rootCA.pem
  register: rootCA_pem
- name: Register rootCA.key
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/rootCA.key
  register: rootCA_key
- name: Register controller.crt
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/controller.crt
  register: controller_crt
- name: Register controller.key
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/controller.key
  register: controller_key
- name: Register admin_operator.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/admin_operator.pem
  register: admin_operator_pem
- name: Register admin_operator.key.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/admin_operator.key.pem
  register: admin_operator_key_pem
- name: Register fluentd.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/fluentd.pem
  register: fluentd_pem
- name: Register fluentd.key
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/fluentd.key
  register: fluentd_key
- name: Register bootstrapper.key
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/bootstrapper.key
  register: bootstrapper_key
- name: Register certifier.key
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/certifier.key
  register: certifier_key
- name: Register certifier.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/certifier.pem
  register: certifier_pem
- name: Register nms_nginx.key.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/nms_nginx.key.pem
  register: nms_nginx_key_pem
- name: Register nms_nginx.pem
  slurp:
    src: /home/{{ ansible_user }}/{{ magma_directory }}/secrets/nms_nginx.pem
  register: nms_nginx_pem
