---
name: Auto Label Pull requests on showtech components
on:  # yamllint disable-line rule:truthy
  # Use pull_request_target to gain write permissions.
  # Ref: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - 'showtech/**'

jobs:
  # This job is to automatically apply lte labels to pull requests
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            var lbl = `component: showtech`

            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [lbl],
            })
