---
name: backport

on:
  push:
    branches:
      - master

jobs:
  backport:
    name: backport
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: "${{ github.workspace }}"
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # pin@v2
        with:
          python-version: '3.7'
      - run: |
          mkdir ~/.magma
          echo ${{ secrets.GITHUB_TOKEN }} > ~/.magma/github_access_token
      - name: Install python prerequisites
        run: pip3 install fabric3 jsonpickle requests PyYAML PyGithub
      - run: |
          cd ${MAGMA_ROOT}/.github/workflows/scripts
          fab find_release_commits
      - name: Extract commit title
        if: failure()
        id: commit
        run: |
          str="$(jq '.head_commit.message' $GITHUB_EVENT_PATH)"    # get the head_commit message
          echo ::set-output name=title::${str%%\\n*} | tr -d '"'
      - name: Notify failure to Slack
        if: failure()
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # pin@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CI }}
          SLACK_TITLE: "Failure of backport on master"
          SLACK_USERNAME: "Back port job"
          SLACK_MESSAGE: "${{ steps.commit.outputs.title}}"
          SLACK_ICON_EMOJI: ":boom:"
          SLACK_COLOR: "#FF0000"
          SLACK_FOOTER: ' '
