---
name: Python Format Check
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v1.*
  pull_request:
    branches:
      - master
      - v1.*
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_not_skip: ${{ steps.changes.outputs.filesChanged }}
    steps:
      # Need to get git on push event
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            filesChanged:
              - [".github/workflows/python-workflow.yml", "**/*.py"]
      # Need to save PR number as Github action does not propagate it with workflow_run event
      - name: Save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo -n ${{ github.event.number }} > ./pr/NR
          echo -n ${{ steps.changes.outputs.filesChanged == 'false' }} > ./pr/skipped
          echo -n "false" > ./pr/RPR
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/

  run-formatters-and-check-for-errors:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_not_skip == 'true' }}
    name: Python Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: py-changes
        # Set outputs.py to be a list of modified python files
        run: |
          echo "::set-output name=py::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .py$ | xargs)"
      - if: ${{ steps.py-changes.outputs.py }}
        name: Build the python-precommit Docker base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./lte/gateway/docker/python-precommit/Dockerfile
          push: false
          tags: magma/py-lint:latest
      - if: ${{ steps.py-changes.outputs.py }}
        name: Format and check for leftover changes
        uses: addnab/docker-run-action@v3
        with:
          image: magma/py-lint:latest
          options: -u 0 -v ${{ github.workspace }}:/code
          run: |
            echo "Running formatting tools. This should be equivalent to running './lte/gateway/python/precommit.py --format --diff' locally."
            for file in ${{ steps.py-changes.outputs.py }};
            do
              set -e
              echo ""
              echo "Running isort on $file...";
              isort --diff --check-only $file;
              echo "Running autopep8 on $file...";
              autopep8 --diff --exit-code --select W191,W291,W292,W293,W391,E131,E2,E3 -r $file;
              echo "Running add-trailing-comma on $file...";
              add-trailing-comma --py35-plus $file;
            done;
      # Need to save PR number as Github action does not propagate it with workflow_run event
      - name: Save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/
